
package tiendaumg.kevin.oliva.pkg9960.pkg19.pkg2073;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class Factura extends javax.swing.JFrame {

private conexionBD conect = new conexionBD();
    public Factura() {
        initComponents();
        this.setLocationRelativeTo(null);
        lblNom.setText(menuPrincipal.txtNombre.getText());
        lblApe.setText(menuPrincipal.txtApellido.getText());
        lblNit.setText(menuPrincipal.txtNit.getText());
        lblDire.setText(menuPrincipal.txtDireccion.getText());
        lblTotalFinal.setText(pedido.lblGranTotal.getText());
    }
void procesar(){
    String nom,ape,nit,dire;
        nom = menuPrincipal.txtNombre.getText();
        ape = menuPrincipal.txtApellido.getText();
        nit = menuPrincipal.txtNit.getText();
        dire = menuPrincipal.txtDireccion.getText();
        String sql = ""; 
        
        sql = "INSERT INTO clientes (nit_clie,nom_clie,ape_clie,dire_clie) VALUES (?,?,?,?)";
        try {
            PreparedStatement pre = conect.conexion.prepareStatement(sql);
            pre.setString(1, nom);
            pre.setString(2, ape);
            pre.setString(3, nit);
            pre.setString(4, dire);
            
            int num = pre.executeUpdate();
            if(num>0){
                JOptionPane.showMessageDialog(null, "Cliente registrado Satisfactoriamente");                
                System.exit(0);
                
            }
        } catch (SQLException ex) {
            
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        lblTituloFactura = new javax.swing.JLabel();
        lblNombreF = new javax.swing.JLabel();
        lblApeF = new javax.swing.JLabel();
        lblNitF = new javax.swing.JLabel();
        lblDireF = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        lblApe = new javax.swing.JLabel();
        lblNit = new javax.swing.JLabel();
        lblDire = new javax.swing.JLabel();
        lblTotalG = new javax.swing.JLabel();
        lblTotalFinal = new javax.swing.JLabel();
        botonProcesar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblTotalLetras = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTituloFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        lblTituloFactura.setText("Factura Tienda Mi UMG");

        lblNombreF.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblNombreF.setText("Nombre:");

        lblApeF.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblApeF.setText("Apellido:");

        lblNitF.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblNitF.setText("NIT:");

        lblDireF.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDireF.setText("Dirección:");

        lblNom.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblNom.setText("NULL");

        lblApe.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblApe.setText("NULL");

        lblNit.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblNit.setText("NULL");

        lblDire.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDire.setText("NULL");

        lblTotalG.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblTotalG.setText("Total gastado: ");

        lblTotalFinal.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblTotalFinal.setText("0.00");
        lblTotalFinal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblTotalFinalPropertyChange(evt);
            }
        });

        botonProcesar.setText("Procesar Compra");
        botonProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProcesarActionPerformed(evt);
            }
        });

        jButton2.setText("Regresar a pedido");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblTotalLetras.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblTotalLetras.setText("Cero");

        jButton3.setText("Total en Letras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel10.setText("Total en letras:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/logo umg1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalLetras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(botonProcesar)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(lblTituloFactura))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(223, 223, 223)
                                .addComponent(jButton2)))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotalG)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotalFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNombreF, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblNom))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblApeF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblApe)))
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNitF)
                                        .addGap(53, 53, 53)
                                        .addComponent(lblNit))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDireF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDire)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                                .addComponent(jLabel1))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTituloFactura)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNombreF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNom))
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNitF)
                                    .addComponent(lblNit))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblApeF)
                                .addComponent(lblApe))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDireF)
                                .addComponent(lblDire))))
                    .addComponent(jLabel1))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalG)
                    .addComponent(lblTotalFinal))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalLetras)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(42, 42, 42)
                .addComponent(botonProcesar)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTotalFinalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblTotalFinalPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTotalFinalPropertyChange

    private void botonProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProcesarActionPerformed
        procesar();
        
    }//GEN-LAST:event_botonProcesarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       double numero =Double.parseDouble(lblTotalFinal.getText());
       lblTotalLetras.setText((String)convertirNumero.numeroTexto(numero));
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton botonProcesar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblApe;
    private javax.swing.JLabel lblApeF;
    private javax.swing.JLabel lblDire;
    private javax.swing.JLabel lblDireF;
    private javax.swing.JLabel lblNit;
    private javax.swing.JLabel lblNitF;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblNombreF;
    private javax.swing.JLabel lblTituloFactura;
    private javax.swing.JLabel lblTotalFinal;
    private javax.swing.JLabel lblTotalG;
    private javax.swing.JLabel lblTotalLetras;
    // End of variables declaration//GEN-END:variables
}
